server:
  port: 8080

spring:
   main:
     web-application-type: servlet
   datasource:
     url: jdbc:postgresql://localhost:5332/customer
     username: marcelle
     password: password
   jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.PostgresSQLDialect
          format_sql: true
      show-sql: true
